# -*- coding: utf-8 -*-
"""Text - Text & text - Image Generation using Generative AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xiuzKQZb-DdAlPdymYpz2mk5EvoPbTuw
"""

!nvidia-smi

import os
os.environ['GEMINI_API_KEY'] = 'AIzaSyB2Bm_-I1lGiwjX9VHUVEl3DdSdGpGkSVA'

!pip install -q -U google-generativeai

import google.generativeai as genai

genai.configure(api_key=os.environ['GEMINI_API_KEY'])

model = genai.GenerativeModel('gemini-1.5-pro')

response = model.generate_content("what is today?")
print (response.text)

model1 = genai.GenerativeModel('gemini-1.5-flash')

response = model.generate_content("what is today?")
print (response.text)

model2 = genai.GenerativeModel('models/gemini-1.5-flash-8b-exp-0924')

response = model.generate_content("what is today?")
print (response.text)

response2 = model2.generate_content("what is life span of person")
print(response2.text)

import pathlib
import textwrap

import google.generativeai as genai

from IPython.display import display
from IPython.display import Markdown


def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# response3 = model2.generate_content("what is the meaning of dream & goal? how to reach the dream")

to_markdown(response3.text)

#!curl -o image.jpg https://t0.gstatic.com/licensed-image?q=tbn:ANd9GcQ_Kevbk21QBRy-PgB4kQpS79brbmmEG7m3VOTShAn4PecDU5H5UxrJxE3Dw1JiaG17V88QIol19-3TM2wCHw

import PIL.Image
img = PIL.Image.open('/content/download (1).jpeg')
img

model4 = genai.GenerativeModel('models/gemini-1.5-flash-8b-exp-0924')

response4 = model4.generate_content(img)

to_markdown(response4.text)

import PIL.Image
img = PIL.Image.open('/content/download.jpeg')
img

response4 = model4.generate_content(img)

to_markdown(response4.text)